// frontend-svelte/src/App.svelte
<script lang="ts">
  import { 
    INITIAL_DESTINATIONS, 
    INITIAL_TRAIN_ROUTES, 
    INITIAL_ISSUES 
  } from './data';
  import type { 
    TrainRoute, 
    Booking, 
    Passenger, 
    ProjectIssue, 
    Destination 
  } from './types';
  import TrainSearchView from './components/TrainSearchView.svelte';
  import SeatSelectionCheckoutView from './components/SeatSelectionCheckoutView.svelte';
  import TicketConfirmationView from './components/TicketConfirmationView.svelte';
  import MyBookingsView from './components/MyBookingsView.svelte';
  import ProjectManagementView from './components/ProjectManagementView.svelte';
  import { 
    Train, 
    Ticket, 
    Search, 
    Compass,
    Layers,
    X
  } from 'lucide-svelte';

  // Navigation tab state - Default is SEARCH (Client Travel Portal)
  let currentView = $state<'search' | 'seat_selection' | 'confirmation' | 'my_bookings'>('search');

  // Academic / Project Documentation Drawer State
  let isDocsDrawerOpen = $state(false);

  // Core application data state
  let destinations = $state<Destination[]>(INITIAL_DESTINATIONS);
  let trains = $state<TrainRoute[]>(INITIAL_TRAIN_ROUTES);
  let issues = $state<ProjectIssue[]>(INITIAL_ISSUES);
  let bookings = $state<Booking[]>([
    {
      id: 'BK-1001',
      bookingCode: 'RW-ES-9841',
      train: INITIAL_TRAIN_ROUTES[0], // Madrid -> Barcelona
      travelDate: '2026-09-20',
      passengers: [
        {
          fullName: 'Lucas Gómez',
          passportId: 'PAS-459201',
          seatId: '2-A',
          seatClass: 'tourist',
          price: 65,
        },
      ],
      totalPrice: 65,
      currency: 'EUR',
      createdAt: '2026-08-14 09:30',
      status: 'confirmed',
      qrPayload: 'RAILWORLD:RW-ES-9841:MAD-BCN:LUCAS_GOMEZ',
      userEmail: 'viajero@busyahurail.com',
    },
  ]);

  // Selected Booking state for checkout / confirmation
  let selectedTrain = $state<TrainRoute | null>(null);
  let selectedTravelDate = $state<string>('2026-09-15');
  let selectedPassengerCount = $state<number>(1);
  let selectedClassPreference = $state<'tourist' | 'first' | 'business'>('tourist');
  let activeBooking = $state<Booking | null>(null);

  // Active Multi-framework Backend selection (Express or FastAPI)
  let activeBackend = $state<'express' | 'fastapi'>('express');
  let selectedCurrency = $state<'EUR' | 'USD' | 'GBP'>('EUR');

  function handleSelectTrain(
    train: TrainRoute, 
    date: string, 
    count: number,
    classTier: 'tourist' | 'first' | 'business' = 'tourist'
  ) {
    selectedTrain = train;
    selectedTravelDate = date;
    selectedPassengerCount = count;
    selectedClassPreference = classTier;
    currentView = 'seat_selection';
    window.scrollTo({ top: 0, behavior: 'smooth' });
  }

  function handleConfirmBooking(passengers: Passenger[], totalPrice: number) {
    if (!selectedTrain) return;

    const dest = destinations.find((d) => d.country.toLowerCase() === selectedTrain.country.toLowerCase());
    const currency = dest ? dest.currency : 'EUR';

    const newBooking: Booking = {
      id: `BK-${Date.now()}`,
      bookingCode: `RW-${selectedTrain.country.substring(0, 2).toUpperCase()}-${Math.floor(1000 + Math.random() * 9000)}`,
      train: selectedTrain,
      travelDate: selectedTravelDate,
      passengers,
      totalPrice,
      currency,
      createdAt: new Date().toISOString().replace('T', ' ').substring(0, 16),
      status: 'confirmed',
      qrPayload: `BUSYAHU-TICKET:${selectedTrain.trainNumber}:${passengers[0]?.fullName}:${selectedTrain.fromCity}-${selectedTrain.toCity}`,
      userEmail: 'viajero@busyahurail.com',
    };

    bookings = [newBooking, ...bookings];
    activeBooking = newBooking;
    currentView = 'confirmation';
    window.scrollTo({ top: 0, behavior: 'smooth' });
  }

  function handleCancelBooking(bookingId: string) {
    bookings = bookings.map((b) => (b.id === bookingId ? { ...b, status: 'cancelled' } : b));
  }

  function handleViewTicket(booking: Booking) {
    activeBooking = booking;
    currentView = 'confirmation';
    window.scrollTo({ top: 0, behavior: 'smooth' });
  }

  function handleUpdateIssueStatus(issueId: string, newStatus: ProjectIssue['status']) {
    issues = issues.map((iss) => (iss.id === issueId ? { ...iss, status: newStatus } : iss));
  }

  let confirmedBookingsCount = $derived(
    bookings.filter((b) => b.status === 'confirmed').length
  );
</script>

<div class="min-h-screen bg-slate-100 text-slate-900 flex flex-col font-sans selection:bg-indigo-500 selection:text-white">
  <!-- CONSUMER TOP NAVBAR: 3-Zone Clean Header -->
  <header class="bg-slate-950 text-white border-b border-slate-800/80 sticky top-0 z-40 backdrop-blur-md bg-slate-950/95">
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 h-18 flex items-center justify-between">
      <!-- Zone 1: Brand Element -->
      <button
        onclick={() => (currentView = 'search')}
        class="flex items-center gap-2.5 text-left group"
      >
        <div class="w-10 h-10 rounded-xl bg-indigo-600 group-hover:bg-indigo-500 flex items-center justify-center text-white shadow-md transition-colors">
          <Train class="w-5 h-5" />
        </div>
        <div>
          <span class="text-xl font-black tracking-tight text-white group-hover:text-indigo-300 transition-colors">
            BusYahu <span class="text-indigo-400 font-extrabold">Rail</span>
          </span>
          <span class="block text-[10px] text-slate-400 font-medium">
            Alta Velocidad & Billetes Oficiales
          </span>
        </div>
      </button>

      <!-- Zone 2: Navigation Links -->
      <nav class="hidden md:flex items-center gap-1.5 lg:gap-3 text-xs font-bold">
        <button
          onclick={() => (currentView = 'search')}
          class="px-3 py-2 rounded-xl transition-colors flex items-center gap-1.5 {currentView === 'search' || currentView === 'seat_selection' ? 'bg-indigo-600/90 text-white shadow-sm' : 'text-slate-300 hover:text-white hover:bg-slate-800/60'}"
        >
          <Search class="w-4 h-4" />
          <span>Comprar Billetes</span>
        </button>

        <button
          onclick={() => {
            currentView = 'search';
            setTimeout(() => {
              const elem = document.getElementById('train-results-section');
              if (elem) elem.scrollIntoView({ behavior: 'smooth' });
            }, 50);
          }}
          class="px-3 py-2 rounded-xl text-slate-300 hover:text-white hover:bg-slate-800/60 transition-colors flex items-center gap-1.5"
        >
          <Compass class="w-4 h-4" />
          <span>Explorar Destinos</span>
        </button>

        <button
          onclick={() => (currentView = 'my_bookings')}
          class="px-3 py-2 rounded-xl transition-colors flex items-center gap-2 {currentView === 'my_bookings' || currentView === 'confirmation' ? 'bg-indigo-600/90 text-white shadow-sm' : 'text-slate-300 hover:text-white hover:bg-slate-800/60'}"
        >
          <Ticket class="w-4 h-4" />
          <span>Mis Billetes</span>
          {#if confirmedBookingsCount > 0}
            <span class="bg-amber-400 text-slate-950 font-black text-[10px] px-1.5 py-0.2 rounded-full tabular-nums">
              {confirmedBookingsCount}
            </span>
          {/if}
        </button>
      </nav>

      <!-- Zone 3: Actions & Academic Trigger -->
      <div class="flex items-center gap-2 sm:gap-3">
        <select
          bind:value={selectedCurrency}
          class="bg-slate-800/80 border border-slate-700 text-slate-200 text-xs font-bold rounded-lg px-2.5 py-1.5 focus:outline-none focus:ring-1 focus:ring-indigo-500"
        >
          <option value="EUR">€ EUR</option>
          <option value="USD">$ USD</option>
          <option value="GBP">£ GBP</option>
        </select>

        <button
          onclick={() => (currentView = 'my_bookings')}
          class="md:hidden p-2 rounded-lg bg-slate-800 text-slate-200 hover:text-white relative"
          title="Mis Billetes"
        >
          <Ticket class="w-4 h-4" />
          {#if confirmedBookingsCount > 0}
            <span class="absolute -top-1 -right-1 bg-amber-400 text-slate-950 font-black text-[9px] w-4 h-4 rounded-full flex items-center justify-center">
              {confirmedBookingsCount}
            </span>
          {/if}
        </button>

        <button
          onclick={() => (isDocsDrawerOpen = true)}
          class="px-2.5 py-1.5 bg-slate-800/90 hover:bg-slate-700 text-slate-300 hover:text-white text-[11px] font-semibold rounded-lg border border-slate-700 transition-colors flex items-center gap-1.5"
          title="Ver Ficha Técnica Universitaria (12 Issues, Docker y Commit Conventions)"
        >
          <Layers class="w-3.5 h-3.5 text-indigo-400" />
          <span class="hidden sm:inline">Ficha Técnica</span>
        </button>
      </div>
    </div>
  </header>

  <!-- MAIN BODY -->
  <main class="flex-1 max-w-7xl w-full mx-auto px-4 sm:px-6 lg:px-8 py-8">
    {#if currentView === 'search'}
      <TrainSearchView
        {destinations}
        {trains}
        {activeBackend}
        onSelectTrain={handleSelectTrain}
        onToggleBackend={(b) => (activeBackend = b)}
        onOpenProjectDocs={() => (isDocsDrawerOpen = true)}
      />
    {:else}
      {#if currentView === 'seat_selection' && selectedTrain}
        <SeatSelectionCheckoutView
          train={selectedTrain}
          travelDate={selectedTravelDate}
          passengerCount={selectedPassengerCount}
          initialClass={selectedClassPreference}
          onBack={() => (currentView = 'search')}
          onConfirmBooking={handleConfirmBooking}
          currencySymbol={destinations.find((d) => d.country.toLowerCase() === selectedTrain?.country.toLowerCase())?.currencySymbol || '€'}
          currency={destinations.find((d) => d.country.toLowerCase() === selectedTrain?.country.toLowerCase())?.currency || 'EUR'}
        />
      {:else}
        {#if currentView === 'confirmation' && activeBooking}
          <TicketConfirmationView
            booking={activeBooking}
            onBackToSearch={() => (currentView = 'search')}
            onGoToMyBookings={() => (currentView = 'my_bookings')}
          />
        {:else}
          {#if currentView === 'my_bookings'}
            <MyBookingsView
              {bookings}
              onCancelBooking={handleCancelBooking}
              onViewTicket={handleViewTicket}
              onGoToSearch={() => (currentView = 'search')}
            />
          {/if}
        {/if}
      {/if}
    {/if}
  </main>

  <!-- ACADEMIC SPECIFICATIONS DRAWER MODAL -->
  {#if isDocsDrawerOpen}
    <div class="fixed inset-0 z-50 overflow-y-auto bg-slate-950/70 backdrop-blur-sm flex justify-end">
      <div class="bg-white w-full max-w-4xl min-h-screen shadow-2xl flex flex-col">
        <div class="bg-slate-900 text-white p-6 flex items-center justify-between border-b border-slate-800 sticky top-0 z-20">
          <div class="flex items-center gap-3">
            <div class="p-2 bg-indigo-600 rounded-xl text-white">
              <Layers class="w-5 h-5" />
            </div>
            <div>
              <h3 class="text-base font-black text-white">
                Ficha Técnica del Proyecto Final · Programación 3
              </h3>
              <p class="text-xs text-slate-400">
                Seguimiento de 12 Issues, Conventional Commits y Arquitectura Docker
              </p>
            </div>
          </div>

          <button
            onclick={() => (isDocsDrawerOpen = false)}
            class="w-9 h-9 rounded-xl bg-slate-800 hover:bg-slate-700 text-slate-300 hover:text-white flex items-center justify-center transition-colors"
          >
            <X class="w-5 h-5" />
          </button>
        </div>

        <div class="p-6 overflow-y-auto flex-1">
          <ProjectManagementView
            {issues}
            onUpdateIssueStatus={handleUpdateIssueStatus}
          />
        </div>
      </div>
    </div>
  {/if}
</div>

// frontend-react/src/App.tsx
import React, { useState } from 'react';
import { Destination, TrainRoute, Booking, Passenger } from './types';
import { Navbar } from './components/Navbar';
import { CountrySelector } from './components/CountrySelector';
import { SeatMap } from './components/SeatMap';
import { ETicketModal } from './components/ETicketModal';
import { MyBookings } from './components/MyBookings';
import { Search, MapPin, Calendar, Clock, ArrowRight, ArrowLeftRight } from 'lucide-react';
import { INITIAL_DESTINATIONS, INITIAL_TRAIN_ROUTES } from './mockData';

const INITIAL_TRAINS: TrainRoute[] = [
  {
    id: 'TR-ES-1', trainNumber: 'AVE 03102', operator: 'Renfe', country: 'España',
    fromCity: 'Madrid', fromStation: 'Madrid Puerta de Atocha',
    toCity: 'Barcelona', toStation: 'Barcelona Sants',
    departureTime: '08:30', arrivalTime: '11:00', duration: '2h 30m',
    basePrice: 65, availableSeatsCount: 42, amenities: ['Wi-Fi 5G', 'Cafetería', 'Toma Corriente'],
    trainModel: 'AVE Serie 103 (310 km/h)'
  },
  {
    id: 'TR-ES-2', trainNumber: 'AVE 03144', operator: 'Renfe', country: 'España',
    fromCity: 'Madrid', fromStation: 'Madrid Puerta de Atocha',
    toCity: 'Barcelona', toStation: 'Barcelona Sants',
    departureTime: '14:00', arrivalTime: '16:45', duration: '2h 45m',
    basePrice: 72, availableSeatsCount: 28, amenities: ['Wi-Fi 5G', 'Silencio', 'Enchufe Individual'],
    trainModel: 'AVE Serie 102 Talgo'
  },
  {
    id: 'TR-FR-1', trainNumber: 'TGV 9204', operator: 'SNCF', country: 'Francia',
    fromCity: 'París', fromStation: 'Paris Gare de Lyon',
    toCity: 'Lyon', toStation: 'Lyon Part-Dieu',
    departureTime: '09:15', arrivalTime: '11:15', duration: '2h 00m',
    basePrice: 58, availableSeatsCount: 60, amenities: ['Bar TGV', 'Wi-Fi Gratuito'],
    trainModel: 'TGV Duplex 2N2'
  },
  {
    id: 'TR-JP-1', trainNumber: 'Nozomi 21', operator: 'JR Central', country: 'Japón',
    fromCity: 'Tokio', fromStation: 'Tokyo Station',
    toCity: 'Kioto', toStation: 'Kyoto Station',
    departureTime: '10:00', arrivalTime: '12:15', duration: '2h 15m',
    basePrice: 13500, availableSeatsCount: 84, amenities: ['Shinkansen Wi-Fi', 'Fumadores', 'Catering'],
    trainModel: 'Shinkansen Series N700S'
  }
];

export default function App() {
  const [currentTab, setCurrentTab] = useState<'search' | 'bookings'>('search');
  const [activeBackend, setActiveBackend] = useState<'express' | 'fastapi'>('express');

  const [selectedCountryId, setSelectedCountryId] = useState<string>('es');
  const currentDestination = INITIAL_DESTINATIONS.find(d => d.id === selectedCountryId) || INITIAL_DESTINATIONS[0];

  const [fromCity, setFromCity] = useState<string>(currentDestination.cities[0]?.name || 'Madrid');
  const [toCity, setToCity] = useState<string>(currentDestination.cities[1]?.name || 'Barcelona');
  const [travelDate, setTravelDate] = useState<string>('2026-10-15');

  const [activeTrain, setActiveTrain] = useState<TrainRoute | null>(null);
  const [isSelectingSeats, setIsSelectingSeats] = useState(false);
  const [activeETicket, setActiveETicket] = useState<Booking | null>(null);
  const [bookings, setBookings] = useState<Booking[]>([]);

  const handleCountryChange = (countryId: string) => {
    setSelectedCountryId(countryId);
    const dest = INITIAL_DESTINATIONS.find(d => d.id === countryId) || INITIAL_DESTINATIONS[0];
    setFromCity(dest.cities[0]?.name || '');
    setToCity(dest.cities[1]?.name || dest.cities[0]?.name || '');
  };

  const handleSwapCities = () => {
    const temp = fromCity;
    setFromCity(toCity);
    setToCity(temp);
  };

  const filteredTrains = INITIAL_TRAINS.filter(
    t => t.country.toLowerCase() === currentDestination.country.toLowerCase() &&
         (!fromCity || t.fromCity.toLowerCase() === fromCity.toLowerCase()) &&
         (!toCity || t.toCity.toLowerCase() === toCity.toLowerCase())
  );

  const handleConfirmSeats = (seats: string[], seatClass: 'tourist' | 'first' | 'business', price: number) => {
    const passengers: Passenger[] = seats.map((s, idx) => ({
      fullName: `Pasajero ${idx + 1}`,
      passportId: `PAS-94820${idx}`,
      seatId: s,
      seatClass,
      price,
    }));

    const newBooking: Booking = {
      id: `BK-${Date.now()}`,
      bookingCode: `BY-${Math.floor(100000 + Math.random() * 900000)}`,
      train: activeTrain!,
      travelDate,
      passengers,
      totalPrice: price * seats.length,
      currency: currentDestination.currencySymbol,
      status: 'confirmed',
      createdAt: new Date().toLocaleDateString('es-ES'),
    };

    setBookings([newBooking, ...bookings]);
    setIsSelectingSeats(false);
    setActiveETicket(newBooking);
  };

  const handleCancelBooking = (bookingId: string) => {
    setBookings(bookings.map(b => b.id === bookingId ? { ...b, status: 'cancelled' } : b));
  };

  return (
    <div className="min-h-screen bg-slate-100 text-slate-900 flex flex-col font-sans">
      <Navbar
        currentTab={currentTab}
        onSelectTab={(tab) => {
          setCurrentTab(tab);
          setIsSelectingSeats(false);
        }}
        activeBackend={activeBackend}
        onToggleBackend={setActiveBackend}
        bookingsCount={bookings.filter(b => b.status === 'confirmed').length}
      />

      <main className="flex-1 max-w-7xl w-full mx-auto px-4 sm:px-6 lg:px-8 py-6 space-y-6">
        
        {/* Modal de E-Ticket emitido */}
        {activeETicket && (
          <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-950/70 backdrop-blur-xs">
            <ETicketModal
              booking={activeETicket}
              onClose={() => setActiveETicket(null)}
            />
          </div>
        )}

        {currentTab === 'search' && (
          <>
            {isSelectingSeats && activeTrain ? (
              <SeatMap
                train={activeTrain}
                date={travelDate}
                currencySymbol={currentDestination.currencySymbol}
                onBack={() => setIsSelectingSeats(false)}
                onConfirmSeats={handleConfirmSeats}
              />
            ) : (
              <>
                {/* 1. Selector de los 11 Países */}
                <CountrySelector
                  destinations={INITIAL_DESTINATIONS}
                  selectedCountryId={selectedCountryId}
                  onSelectCountry={handleCountryChange}
                />

                {/* 2. Buscador de Trayectos */}
                <div className="bg-white border border-slate-200 rounded-3xl p-5 sm:p-6 shadow-sm space-y-4">
                  <h3 className="text-xs font-bold uppercase tracking-wider text-slate-500">
                    Paso 2: Define tu Trayecto y Fecha
                  </h3>

                  <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-12 gap-3 items-end">
                    <div className="lg:col-span-4">
                      <label className="block text-xs font-bold text-slate-700 mb-1.5 flex items-center gap-1.5">
                        <MapPin className="w-3.5 h-3.5 text-indigo-600" /> Origen
                      </label>
                      <select
                        value={fromCity}
                        onChange={(e) => setFromCity(e.target.value)}
                        className="w-full bg-slate-50 border border-slate-300 text-slate-900 rounded-xl px-3.5 py-2.5 text-xs sm:text-sm font-semibold"
                      >
                        {currentDestination.cities.map((c) => (
                          <option key={c.name} value={c.name}>{c.name} ({c.station})</option>
                        ))}
                      </select>
                    </div>

                    <div className="hidden lg:flex lg:col-span-1 justify-center pb-1">
                      <button
                        type="button"
                        onClick={handleSwapCities}
                        className="p-2.5 rounded-xl border border-slate-200 hover:bg-slate-50 text-slate-600 cursor-pointer"
                      >
                        <ArrowLeftRight className="w-4 h-4" />
                      </button>
                    </div>

                    <div className="lg:col-span-4">
                      <label className="block text-xs font-bold text-slate-700 mb-1.5 flex items-center gap-1.5">
                        <MapPin className="w-3.5 h-3.5 text-emerald-600" /> Destino
                      </label>
                      <select
                        value={toCity}
                        onChange={(e) => setToCity(e.target.value)}
                        className="w-full bg-slate-50 border border-slate-300 text-slate-900 rounded-xl px-3.5 py-2.5 text-xs sm:text-sm font-semibold"
                      >
                        {currentDestination.cities.map((c) => (
                          <option key={c.name} value={c.name}>{c.name} ({c.station})</option>
                        ))}
                      </select>
                    </div>

                    <div className="lg:col-span-3">
                      <label className="block text-xs font-bold text-slate-700 mb-1.5 flex items-center gap-1.5">
                        <Calendar className="w-3.5 h-3.5 text-slate-600" /> Fecha del Viaje
                      </label>
                      <input
                        type="date"
                        value={travelDate}
                        onChange={(e) => setTravelDate(e.target.value)}
                        className="w-full bg-slate-50 border border-slate-300 text-slate-900 rounded-xl px-3 py-2 text-xs sm:text-sm font-semibold"
                      />
                    </div>
                  </div>
                </div>

                {/* 3. Resultados de Trenes */}
                <div className="space-y-4">
                  <h3 className="text-base font-extrabold text-slate-900 flex items-center gap-2">
                    <span>Trenes Disponibles en {currentDestination.country}</span>
                    <span className="text-xs bg-indigo-100 text-indigo-800 px-2.5 py-0.5 rounded-full font-mono font-bold">
                      {filteredTrains.length} servicios
                    </span>
                  </h3>

                  {filteredTrains.length === 0 ? (
                    <div className="bg-white border border-slate-200 rounded-3xl p-12 text-center space-y-3 shadow-sm">
                      <div className="text-base font-bold text-slate-800">
                        No hay trenes programados para {fromCity} ➔ {toCity}
                      </div>
                      <p className="text-xs text-slate-500">
                        Prueba invirtiendo las ciudades o selecciona España, Francia o Japón.
                      </p>
                      <button
                        type="button"
                        onClick={handleSwapCities}
                        className="px-4 py-2 bg-indigo-50 hover:bg-indigo-100 text-indigo-700 text-xs font-bold rounded-xl cursor-pointer"
                      >
                        Invertir a {toCity} ➔ {fromCity}
                      </button>
                    </div>
                  ) : (
                    filteredTrains.map((train) => (
                      <div
                        key={train.id}
                        className="bg-white border border-slate-200 hover:border-indigo-500 rounded-3xl p-5 sm:p-6 shadow-sm hover:shadow-md transition-all flex flex-col lg:flex-row lg:items-center lg:justify-between gap-5"
                      >
                        <div className="space-y-3 flex-1">
                          <div className="flex items-center gap-2">
                            <span className="px-3 py-1 bg-indigo-50 text-indigo-800 border border-indigo-200 rounded-lg text-xs font-black">
                              {train.operator}
                            </span>
                            <span className="text-xs font-mono font-bold text-slate-700 bg-slate-100 px-2 py-0.5 rounded">
                              {train.trainNumber}
                            </span>
                            <span className="text-xs text-slate-500 font-medium">
                              {train.trainModel}
                            </span>
                          </div>

                          <div className="flex items-center gap-6 pt-1">
                            <div>
                              <div className="text-2xl font-extrabold text-slate-900">{train.departureTime}</div>
                              <div className="text-xs font-bold text-slate-700">{train.fromCity}</div>
                            </div>
                            <div className="flex flex-col items-center">
                              <span className="text-[11px] font-mono text-slate-500 flex items-center gap-1">
                                <Clock className="w-3.5 h-3.5 text-slate-400" /> {train.duration}
                              </span>
                              <div className="w-24 sm:w-36 h-1 bg-slate-200 rounded-full my-1"></div>
                              <span className="text-[10px] text-indigo-700 font-bold font-mono">Directo</span>
                            </div>
                            <div>
                              <div className="text-2xl font-extrabold text-slate-900">{train.arrivalTime}</div>
                              <div className="text-xs font-bold text-slate-700">{train.toCity}</div>
                            </div>
                          </div>

                          <div className="flex flex-wrap gap-2 pt-1">
                            {train.amenities.map((item, i) => (
                              <span key={i} className="text-[11px] bg-slate-50 text-slate-600 border border-slate-200 px-2.5 py-0.5 rounded-full font-medium">
                                ✓ {item}
                              </span>
                            ))}
                          </div>
                        </div>

                        <div className="flex lg:flex-col items-center lg:items-end justify-between border-t lg:border-t-0 pt-4 lg:pt-0 border-slate-100 gap-3">
                          <div className="text-left lg:text-right">
                            <div className="text-[10px] uppercase font-bold text-slate-400">Desde</div>
                            <div className="text-2xl font-black text-slate-900">
                              {currentDestination.currencySymbol}{train.basePrice}
                            </div>
                          </div>
                          <button
                            type="button"
                            onClick={() => {
                              setActiveTrain(train);
                              setIsSelectingSeats(true);
                            }}
                            className="px-5 py-3 bg-indigo-600 hover:bg-indigo-700 text-white text-xs font-bold rounded-2xl shadow-md flex items-center gap-2 cursor-pointer"
                          >
                            <span>Seleccionar Asientos</span>
                            <ArrowRight className="w-4 h-4" />
                          </button>
                        </div>
                      </div>
                    ))
                  )}
                </div>
              </>
            )}
          </>
        )}

        {currentTab === 'bookings' && (
          <MyBookings
            bookings={bookings}
            onCancelBooking={handleCancelBooking}
            onViewTicket={(b) => setActiveETicket(b)}
            onGoToSearch={() => setCurrentTab('search')}
          />
        )}

      </main>
    </div>
  );
}
